#Production New new Oauth2 flow
salesforce:
  clientid: "![8bhXm17IH29j7KIdA1vLaqVnXaYjgiRGtCbScUtQ+hU+8MkTgbZtqllSuTG3Zs4QMoceVnxf/VldjbjsPB1axT9ZhzdIEQvqNNSFbYsc4mZ2EP797VI6hr3X4liuMfnl]"
  secret: "![2rRnDCOpY0eIPAJVKOAtPwHIwSWiq2epGg7wDV9Y+6I/MrrrV0KK24n7INxzt0LL8F9di5TKTFod/RL9aZ+Fn5NOXPSqhaUlObVJMDH+WQE=]"
  
  
helioscope:
  access_token: "![SmRXacVmTvmn+H+RtY8hcEm2Vi9iQGJFOCan0+X1eQCEPK0IjW/fWFMBJkw7Hcqw]"
  helioscope.access_token: "![SmRXacVmTvmn+H+RtY8hcEm2Vi9iQGJFOCan0+X1eQCEPK0IjW/fWFMBJkw7Hcqw]"